### ISSUE TITLE
ICE STORM + FROZEN != MORE DPS SMH

### ISSUE THREAD

**Issue by converal** [drg-tools/drg-weapons-calculator#53]
![image](https://user-images.githubusercontent.com/16324267/141680282-d4f98141-a611-4bc9-a5a4-3d859fc396ba.png)
![image](https://user-images.githubusercontent.com/16324267/141680292-6a5a3c18-0482-42d0-94bf-c8f2fa0ce2bd.png)

**Comment by converal** [comment]
I see there's avg multiplier being used instead but it should be optional

**Comment by converal** [comment]
Ahh, I changed my mind, it's ok :D I just wanna check Ice Storm DpS against individual creatures, mb it's possible to calc individual avg multipliers and show the list of dps against every creature like wip ttk?

**Comment by phg49389** [comment]
Fixed.
